import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

/**
 * The build picks the API address, not the user.
 *
 * A text field for the server address used to be a phishing vector: the
 * token rides in a header to whatever address is set, so "point it here to
 * get package X" would hand over the account. There are only two sensible
 * values, so the build mode picks one:
 *
 *   npm run dev    -> localhost (run `wrangler dev` in another terminal)
 *   npm run build  -> the production worker
 *
 * MARKETPLACE_API_URL overrides either — useful when 8787 is taken, or when
 * running a separate marketplace instance.
 */
const DEV_API_URL = 'http://127.0.0.1:8787';
const PROD_API_URL = 'https://notes-hub-api.appflowly.com';

const override = process.env.MARKETPLACE_API_URL?.trim();
const apiBaseUrl = assertSafeApiUrl(override || (prod ? PROD_API_URL : DEV_API_URL));

console.log(`[marketplace] API: ${apiBaseUrl}${prod ? '' : ' (dev)'}`);

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	// Read by src/constants.ts. JSON.stringify because esbuild's `define`
	// does a raw text substitution — without quotes the address would land
	// in the code as a bare expression.
	define: {
		__API_BASE_URL__: JSON.stringify(apiBaseUrl),
	},
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}

/**
 * Same checks as assertSafeApiUrl() in src/api/api.ts, run at build time
 * instead: a typo in the address should fail the build, not the user's
 * first request. The duplication is deliberate — this file can't import TS
 * modules, and pulling in a bundler for thirty lines isn't worth it.
 *
 * Returns the address normalized (no trailing slash), so main.js ends up
 * with exactly the form we later concatenate with each endpoint path.
 */
function assertSafeApiUrl(raw) {
	let url;
	try {
		url = new URL(raw);
	} catch {
		throw new Error(`The API address is not a valid URL: ${raw}`);
	}

	const localhost = ['localhost', '127.0.0.1', '::1', '[::1]'].includes(url.hostname);
	// http:// sends the token in plaintext, and it never expires. Localhost
	// is exempt — that's wrangler dev, and traffic never leaves the machine.
	if (url.protocol !== 'https:' && !localhost) {
		throw new Error(`The API address must use https:// (localhost is the exception): ${raw}`);
	}
	if (url.username || url.password) {
		throw new Error(`The API address cannot contain a username or password: ${raw}`);
	}
	if (url.search || url.hash) {
		throw new Error(`The API address cannot contain query parameters or a fragment: ${raw}`);
	}

	return url.origin + url.pathname.replace(/\/+$/, '');
}
